/**
 * One-off asset pipeline. Run: node scripts/build-brand.mjs
 *
 * Turns the supplied Drive PNGs into web assets, and rewrites the fetched
 * Google Fonts CSS to point at self-hosted WOFF2 (§9.2 — no third-party font
 * CDN: it removes a DNS lookup and connection on high-latency Nepali mobile,
 * and keeps a clean privacy posture for NGO and international clients).
 */
import sharp from 'sharp';
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const SRC = 'brand/source';
const OUT = 'public';

await mkdir(`${OUT}/brand`, { recursive: true });

/* ---------------------------------------------------------------- images */

// asset-1 — horizontal lockup, transparent. Header use.
await sharp(`${SRC}/asset-1.png`)
  .resize({ height: 240, withoutEnlargement: true })
  .png({ compressionLevel: 9, palette: true })
  .toFile(`${OUT}/brand/lockup.png`);

await sharp(`${SRC}/asset-1.png`)
  .resize({ height: 240, withoutEnlargement: true })
  .webp({ quality: 90 })
  .toFile(`${OUT}/brand/lockup.webp`);

// asset-2 — square mark, transparent. Favicons and avatars.
for (const size of [512, 192, 180, 32]) {
  await sharp(`${SRC}/asset-2.png`)
    .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png({ compressionLevel: 9 })
    .toFile(`${OUT}/brand/mark-${size}.png`);
}

// asset-3 — banner. Open Graph card at the 1.91:1 ratio social platforms crop to.
await sharp(`${SRC}/asset-3.png`)
  .resize(1200, 630, { fit: 'cover', position: 'left' })
  .jpeg({ quality: 86, mozjpeg: true })
  .toFile(`${OUT}/og-default.jpg`);

// The FLAT lockup sitting in the top-left of the banner is materially better
// than the 3D version: it holds together at small sizes and would survive
// single-colour reproduction. Extracted here so it is on record as the
// preferred mark once someone redraws it as vector.
await sharp(`${SRC}/asset-3.png`)
  .extract({ left: 88, top: 78, width: 1010, height: 275 })
  .png({ compressionLevel: 9 })
  .toFile(`brand/flat-lockup-REFERENCE.png`);

await sharp(`${SRC}/asset-3.png`)
  .extract({ left: 88, top: 78, width: 280, height: 275 })
  .png({ compressionLevel: 9 })
  .toFile(`brand/flat-mark-REFERENCE.png`);

console.log('images ✓');

/* ----------------------------------------------------------------- fonts */

const FACES = [
  { slug: 'manrope', family: 'Manrope' },
  { slug: 'jakarta', family: 'Plus Jakarta Sans' },
  { slug: 'deva', family: 'Noto Sans Devanagari' },
];

let css = `/* Self-hosted webfonts — generated by scripts/build-brand.mjs.
   Do not edit by hand. No third-party font CDN (§9.2). */\n\n`;

for (const { slug, family } of FACES) {
  const raw = await readFile(`/tmp/${slug}.css`, 'utf8');
  let n = 0;
  const rewritten = raw
    .replace(/https:\/\/fonts\.gstatic\.com\/[^)]*\.woff2/g, () => `/fonts/${slug}-${++n}.woff2`)
    .replace(/font-display:\s*\w+/g, 'font-display: swap');
  css += `/* ---- ${family} ---- */\n${rewritten.trim()}\n\n`;
}

await writeFile('src/styles/fonts.css', css);
console.log('fonts ✓');
